language: android

sudo: false

jdk: oraclejdk8

android:
  components:
    - tools
    - tools # To fix https://github.com/travis-ci/travis-ci/issues/6040
    - platform-tools
    - build-tools-25.0.3
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - '.+' # Accept all licenses

before_install:
  - ./travis/scripts/decode_private_configs.sh

install:
  # Extracts build configs into source tree
  - tar zxf travis/configs/twidere_private_config.tar.gz

script: ./gradlew clean build

deploy:
  - provider: releases
    prerelease: false
    api_key:
      secure: "eVupX+wQ8+z3F8eKjfm7uTXDBm1ID6SRtlptcMx6QHPCgkoxEYq1nyupuqjiylO6VTZ+gUWbjUYPOwQgXPKP6TlhySXrIoOXicX/mNARqblBh8HXKnnpFqzYlTRsysrX9OqvVGJbT0sRulLIPO4vN+29mHx3oQuRVBRP2a8fiQbJHE5grp/Jte72hmgULAV5wHEtkApxvOT0sJMGYSUQHgt5iPFacfVsQdpp9KhHtO01uVAhMP67BRFdEyaGyqSec8wJvjrIvkLiKwZvW1ZTLybmYVwchEOxJMBOll4GZGwCiqiWKETq/P8QGnlLKTwxrZuVjPfHXahE7+KCYpXt3GVGV05KUKlCVgYkAzKXoaz9zI6UKcspcI52vEZOFpPmSFt0FTzyALJgcdvbTf20BeOIdikNH4D9cvkQAGy8Gq2mqYsDItf6UC7o11BvYPSqs5U5UpAdMSowzqryKaYOrdv641FMG0qNJtRWgae0UbzpsPdJYkWr3u37yrMnIzlAejWZLE95AoheAQN8P1PPGbhSwIoygZ3kl2YoXQoJvPhNkl7THCbE0+LxHLSknVGRVMmEw7kg24dsDK6uQ1ngC2C6WU1RU4jCxyVS23vi1JYMh8YO9CKo9zdCt3u241zCWaL5u5dScPxyeb+0f4Z3BJEzF1csVHLD7LCK+eh88uE="
    file_glob: true
    file: '**/*-release.apk'
    on:
      repo: TwidereProject/Twidere-Android-Emoji-Twemoji
      tags: true