language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    MALLOC_ARENA_MAX=2
    GRADLE_OPTS=-Xmx2048m -Dorg.gradle.parallel=false

addons:
  apt:
    packages:
      - tar
      - gzip
      - patch

before_install:
  - openssl aes-256-cbc -K $encrypted_d849b91c48cc_key -iv $encrypted_d849b91c48cc_iv -in travis/configs/twidere_private_config.tar.gz.enc -out travis/configs/twidere_private_config.tar.gz -d

install:
  # Extracts build configs into source tree
  - tar zxf travis/configs/twidere_private_config.tar.gz

script: ./gradlew build --no-daemon --stacktrace

deploy:
  provider: releases
  prerelease: false
  api_key:
    secure: eVupX+wQ8+z3F8eKjfm7uTXDBm1ID6SRtlptcMx6QHPCgkoxEYq1nyupuqjiylO6VTZ+gUWbjUYPOwQgXPKP6TlhySXrIoOXicX/mNARqblBh8HXKnnpFqzYlTRsysrX9OqvVGJbT0sRulLIPO4vN+29mHx3oQuRVBRP2a8fiQbJHE5grp/Jte72hmgULAV5wHEtkApxvOT0sJMGYSUQHgt5iPFacfVsQdpp9KhHtO01uVAhMP67BRFdEyaGyqSec8wJvjrIvkLiKwZvW1ZTLybmYVwchEOxJMBOll4GZGwCiqiWKETq/P8QGnlLKTwxrZuVjPfHXahE7+KCYpXt3GVGV05KUKlCVgYkAzKXoaz9zI6UKcspcI52vEZOFpPmSFt0FTzyALJgcdvbTf20BeOIdikNH4D9cvkQAGy8Gq2mqYsDItf6UC7o11BvYPSqs5U5UpAdMSowzqryKaYOrdv641FMG0qNJtRWgae0UbzpsPdJYkWr3u37yrMnIzlAejWZLE95AoheAQN8P1PPGbhSwIoygZ3kl2YoXQoJvPhNkl7THCbE0+LxHLSknVGRVMmEw7kg24dsDK6uQ1ngC2C6WU1RU4jCxyVS23vi1JYMh8YO9CKo9zdCt3u241zCWaL5u5dScPxyeb+0f4Z3BJEzF1csVHLD7LCK+eh88uE=
  file_glob: true
  file: '**/*-release.apk'
  on:
    repo: TwidereProject/Twidere-Android-Emoji-Noto
    tags: true